require "user.util"
require "user.launch"
require "user.options"
require "user.title"
require "user.keymaps"
require "user.autocmds"

spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.wakatime"
spec "user.conform"
spec "user.spectre"
-- spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.none-ls"
spec "user.illuminate"
spec "user.gitsigns"
spec "user.whichkey"
-- spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
-- spec "user.harpoon"
-- spec "user.neotest"
spec "user.autopairs"
-- spec "user.neogit"
-- spec "user.alpha"
spec "user.project"
spec "user.indentline"
spec "user.toggleterm"
spec "user.submodules"
spec "user.extras.copilot"
spec "user.virtual-column"

require "user.lazy"
